### ISSUE TITLE
Add PhpSpec to the test tools

### ISSUE THREAD

**Issue by Exadra37** [Exadra37/package-skeleton#12]
I have been playing with this amazing tool for 1 week and i am convinced about is utility to design better code.

http://phpspec.readthedocs.org/en/latest/

**Comment by bmitch** [comment]
:+1:

**Comment by ghost** [comment]
@Exadra37 @bmitch In relation to a4cc725664743e1d27e4a4f70db27692d2abedce could it be an idea to rename the `test\spec` folder to `test\unit` to keep the `test` folder agnostic to the test framework?

It could also make sense to also add `test/functional` to differentiate between the general types of testing.

```
test/unit/Controllers/.gitkeep
test/unit/Exceptions/.gitkeep
test/unit/Formatters/.gitkeep
...
test/functional/.gitkeep
```

Users can then use any test framework (or a mixture of) and the same folder structure would be maintained across all future projects.
- PHPSpec - `unit`
- Behat - `functional`
- PHPUnit - `both`

**Comment by Exadra37** [comment]
The way PhpSpec works, it is looking for `spec` folder. 

Besides that PhpSpec are not unit tests, they call it specifications.

This test framework is very opinionated how test should be done... it will not help you in anyway to get around bad design in the code you want to test,  like Mockery or Codeception.

Behat works with `features` folder and can be used to write functional or acceptance tests.

Resuming, both PhpSpec and Behat will expect their specific folders.

I understand your idea, but is not a good match for this test Frameworks.

**Comment by ghost** [comment]
In that case could we add multiple folders instead? `unit`, `functional`, `spec`, `features` etc so that way people can still choose their testing framework while a standard structure across projects would remain. If they don't choose to use a specific framework the folders would remain unused.

I understand on one hand it makes sense to let people decide their own folders within the test folder but if a standard folder structure exists, I think it would encourage people to separate tests both by type (unit and functional for example) and hierarchy (Controllers, Exceptions, Formatters) rather than using their own choice of testing framework and bundling the tests into a single folder..

```
test/features/.gitkeep
test/functional/.gitkeep
test/spec/Controllers/.gitkeep
test/spec/Exceptions/.gitkeep
test/spec/Formatters/.gitkeep
...
test/unit/Controllers/.gitkeep
test/unit/Exceptions/.gitkeep
test/unit/Formatters/.gitkeep
...
```

**Comment by Exadra37** [comment]
@r34ch for me your last proposal is a good one to go :+1:
